import { useState, useEffect, useRef } from 'react';

interface ProblemMockProps {
    counter: number;
}

export default function ProblemMock({ counter }: ProblemMockProps) {
    const [displayText, setDisplayText] = useState('');
    const prevCounterRef = useRef(counter); // Using useRef to persist previous counter value

    const resources = ['anchor.pdb', 'target.pdb', 'candidate.pdb', 'simulationResults.xyz', 'paper.txt'];

    const resourceDescriptions: Record<string, string> = {
        'anchor.pdb': 'An Anchor serves as a starting point for the drug discovery process. An Anchor is usually an existing, though suboptimal, drug (also known as a ligand) for the target disease. Anchors are represented as .pdb (Protein Data Bank) files or SMILES strings, both used to depict molecular structures.',
        'target.pdb': 'The Target is a protein that is known to play a role in the target disease. The AI uses the Anchor to generate a Candidate that is predicted to bind to the Target.',
        'candidate.pdb': 'The Candidate is a molecule that is generated by the AI based on the Anchor and the Target. The Candidate is predicted to bind to the Target and has the potential to be developed into a drug for the target disease.',
        'simulationResults.xyz': 'This is the output of a simulation that tests the Candidate\'s ability to bind to the Target. The .xyz extension indicates that the results consist of files in various file formats.',
        'paper.txt': 'An academic Paper that documents the Agent’s reasoning, the simulation process, and outcomes, offering suggestions for further action or future research.',
    };

    useEffect(() => {
        setDisplayText('');
        prevCounterRef.current = counter; // Update previous counter after render
    }, [counter]);

    const handleClick = (resource: string) => {
        setDisplayText(resourceDescriptions[resource]);
        console.log(resource);
    };

    const foo = (counter: number): number => {
        switch (counter) {
            case 0: return 0;
            case 1: return 2;
            case 2: return 2;
            case 3: return 3;
            case 4: return 3;
            case 5: return 4;
            case 6: return 4;
            case 7: return 5;
            default: return 5; // Prevents undefined results
        }
    };

    const bar = (counter: number): number[] => {
        switch (counter) {
            case 0: return [];
            case 1: return [0, 1];
            case 2: return [0, 1];
            case 3: return [2];
            case 4: return [2];
            case 5: return [3];
            case 6: return [3];
            case 7: return [4];
            default: return [4]; // Prevents undefined results
        }
    };

    const currentCount = foo(counter);
    const highlightedItems = bar(counter); // Get indices of items to be highlighted

    return (
        <div className='flex flex-col items-center w-full h-full p-4 bg-transparent'>
            <ul className='list-none p-0'>
                {resources.slice(0, currentCount).map((resource, index) => (
                    <li
                        key={resource}
                        onClick={() => handleClick(resource)}
                        className={`cursor-pointer p-2 m-2 bg-yellow-500 text-white rounded hover:bg-yellow-700 transition-colors 
                        ${highlightedItems.includes(index) ? 'border-4 border-black' : ''}`}
                    >
                        {resource}
                    </li>
                ))}
            </ul>
            <p className='mt-24'>{displayText}</p>
        </div>
    );
}
